version: '3.8'
services:
  fastapi_app:
    build:
      context: .
      args:
        APP_PORT: ${APP_LOCAL_PORT-8000}
    ports:
      - '8000:8000'
    secrets:
      - key_encode_secret_key
      - access_token_secret_key
      - refresh_token_secret_key
      - db_password
      - google_oauth2_config
      - github_oauth2_config
    env_file:
      - ${ENV_FILE-app/.env}
    environment:
      - POSTGRES_HOST=postgres_db
      - REDIS_HOST=redis
      - ACCESS_TOKEN_SECRET_KEY_FILE=/run/secrets/access_token_secret_key
      - REFRESH_TOKEN_SECRET_KEY_FILE=/run/secrets/refresh_token_secret_key
      - KEY_ENCODE_SECRET_KEY_FILE=/run/secrets/key_encode_secret_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - GOOGLE_OAUTH2_CONFIG_FILE=/run/secrets/google_oauth.json
      - GITHUB_OAUTH2_CONFIG_FILE=/run/secrets/github_oauth.json
    depends_on:
      - postgres_db
      - redis

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes


  postgres_db:
    image: postgres:latest
    restart: always
    secrets:
      - db_password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    expose:
      - 5432
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:

secrets:
  db_password:
    file: ${POSTGRES_PASSWORD_FILE}
  access_token_secret_key:
    file: ${ACCESS_TOKEN_SECRET_KEY_FILE}
  refresh_token_secret_key:
    file: ${REFRESH_TOKEN_SECRET_KEY_FILE}
  key_encode_secret_key:
    file: ${KEY_ENCODE_SECRET_KEY_FILE}
  google_oauth2_config:
    file: ${GOOGLE_OAUTH2_CONFIG_FILE}
  github_oauth2_config:
    file: ${GITHUB_OAUTH2_CONFIG_FILE}
