"""Connect user and prompts

Revision ID: 1d53b317bbf0
Revises: e2f88fbe105e
Create Date: 2023-12-05 20:11:00.068317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d53b317bbf0'
down_revision: Union[str, None] = 'e2f88fbe105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_prompt', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('system_prompt', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('system_prompt', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'system_prompt', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('datetime_registered', sa.DateTime(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=320),
               existing_nullable=False)
    op.drop_column('user', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_column('user', 'datetime_registered')
    op.drop_constraint(None, 'system_prompt', type_='foreignkey')
    op.alter_column('system_prompt', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('system_prompt', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('system_prompt', 'user_id')
    # ### end Alembic commands ###
