"""New test revision

Revision ID: 40a329b48e43
Revises: 5d76692194bc
Create Date: 2023-09-09 23:03:13.760030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a329b48e43'
down_revision: Union[str, None] = '5d76692194bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chats', column_name='created_at',
        existing_type=sa.DateTime(), type_=sa.DateTime(timezone=True),
    )
    op.alter_column(
        'chats', column_name='last_updated',
        existing_type=sa.DateTime(), type_=sa.DateTime(timezone=True),
    )
    op.alter_column(
        'messages', column_name='created_at',
        existing_type=sa.DateTime(), type_=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chats', column_name='created_at',
        existing_type=sa.DateTime(timezone=True), type_=sa.DateTime(),
    )
    op.alter_column(
        'chats', column_name='last_updated',
        existing_type=sa.DateTime(timezone=True), type_=sa.DateTime(),
    )
    op.alter_column(
        'messages', column_name='created_at',
        existing_type=sa.DateTime(timezone=True), type_=sa.DateTime(),
    )
    # ### end Alembic commands ###
