"""Add prompt table

Revision ID: 52d798071771
Revises: 40a329b48e43
Create Date: 2023-09-16 02:16:35.898572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '52d798071771'
down_revision: Union[str, None] = '40a329b48e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'system_prompt',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('content', sa.TEXT(), nullable=False),
        sa.Column('popularity', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_prompt')
    # ### end Alembic commands ###
