"""Add cascade deletions

Revision ID: 6bb30ec0d9f0
Revises: 485bf3dcd247
Create Date: 2024-03-04 01:33:57.839223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb30ec0d9f0'
down_revision: Union[str, None] = '485bf3dcd247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_key_user_id_fkey', 'api_key', type_='foreignkey')
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('system_prompt_user_id_fkey', 'system_prompt', type_='foreignkey')
    op.create_foreign_key(None, 'system_prompt', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_prompt', type_='foreignkey')
    op.create_foreign_key('system_prompt_user_id_fkey', 'system_prompt', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.create_foreign_key('api_key_user_id_fkey', 'api_key', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
