"""Added is_guest user field

Revision ID: ad33621328bc
Revises: 123a89d3834f
Create Date: 2023-12-03 02:27:57.181834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad33621328bc'
down_revision: Union[str, None] = '123a89d3834f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_guest', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_guest')
    # ### end Alembic commands ###
