"""Added expiry_time user field

Revision ID: e2f88fbe105e
Revises: ad33621328bc
Create Date: 2023-12-03 02:55:12.371301

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f88fbe105e'
down_revision: Union[str, None] = 'ad33621328bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.alter_column('user', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'expiry_date')
    # ### end Alembic commands ###
